services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: "fastapi_app"
    command: ["uvicorn", "core.main:app", "--host", "0.0.0.0", "--port", "80"]
    volumes:
      - .:/core
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379